name: Run tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Install CI dependencies
        run: npm ci

      - name: Install playwright
        run: npx playwright install --with-deps

      - name: Run unit- & E2E-tests
        env:
          API_KEY: ${{ secrets.API_KEY }}
        run: |
          VITE_API_KEY="${API_KEY}" npm run build
          npm run preview &
          npm run test

  deploy:
    name: deploy
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
    needs: build

    steps:
      - uses: actions/checkout@v2
      - name: Deploy to AWS EC2
        env:
          PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEY }}
          HOSTNAME: ${{ secrets.HOSTNAME }}

        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ubuntu@${HOSTNAME} '

            cd tretton37-worksample &&
            git pull origin master &&
            docker build -t tretton37-colleagues . &&
            docker stop tretton37-colleagues &&
            docker rm tretton37-colleagues &&
            docker run -d -p 80:80 --name tretton37-colleagues tretton37-colleagues
          '
